# Generated by Django 4.2.7 on 2024-02-01 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_plan_planfeature_userprofile_delete_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='name',
        ),
    ]
