# Generated by Django 4.2.7 on 2024-02-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_profile_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(default='+63', max_length=11),
        ),
    ]
