# Generated by Django 4.2.7 on 2024-02-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_profile_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planfeature',
            name='title',
            field=models.TextField(max_length=150),
        ),
    ]
