# Generated by Django 4.2.7 on 2024-02-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_planfeature_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
