# Generated by Django 4.2.7 on 2024-02-03 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0014_remove_membership_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='duration',
            new_name='duration_days',
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
