# Generated by Django 4.2.7 on 2024-02-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_remove_payment_plan_remove_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
