# Generated by Django 4.2.7 on 2024-02-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_payment_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('gcash', 'Gcash'), ('paymaya', 'PayMaya')], max_length=50),
        ),
    ]
