# Generated by Django 4.2.7 on 2024-02-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_adminprofile_delete_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
